<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "trb_pi_portfolio"
 *
 * Auto generated by Extension Builder 2014-05-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TRB Plugin: Portfolio',
	'description' => 'This extension adds portfolio content element with Extbase/Fluid rendering. Slider & Filter need are not implemented yet.',
	'category' => 'plugin',
	'author' => 'Boris Günther',
	'author_email' => 'info@boris-guenther.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '2.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'trb_basics' => '2.0',
			'trb_basics_typoscript' => '2.0',
			'trb_basics_viewhelper' => '2.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);